# Generated by Django 3.2.4 on 2021-08-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(blank=True, max_length=50, null=True)),
                ('industry', models.CharField(blank=True, max_length=50, null=True)),
                ('updatedTime', models.CharField(blank=True, max_length=50, null=True)),
                ('recentQuarter', models.IntegerField(blank=True, null=True)),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('ipoyear', models.CharField(blank=True, max_length=10, null=True)),
                ('fullName', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
